server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        address-api:
          clientId: customer-service
          clientSecret: gzu9gPIrRL6BpbRonbeLyouVbeF2E9sA
          accessTokenUri: http://192.168.229.129:38080/realms/address-service/protocol/openid-connect/token

keycloak:
  auth-server-url: http://192.168.229.129:38080
  realm: customer-service
  resource: customer-service
  bearer-only: true

auth:
  enabled: true
  ignored:
    urls: /customer-api/swagger-ui/**, /customer-api/api-docs, /customer-api/api-docs/*, /actuator/**

customer:
  file:
    url: src/main/resources/data/customers.json

rest:
  address-service:
    uri: http://localhost:8082/address-api/addresses

cache:
  clean:
    intervalInMilliseconds: 20000


management:
  endpoints:
    web:
      exposure:
        include: health, info, heapdump, threaddump, metrics
  info:
    env:
      enabled: true
info:
  contributors:
    - Ilker Yaman
    - Sinan Bulubay
    - Gizem Solum
    - Abdul Samet Altunsoy

spring-doc:
  packages-to-scan: com.nsc.customer.controller
  api-docs:
    enabled: true
    path: /customer-api/api-docs
  swagger-ui:
    path: /customer-api/swagger-ui

