server:
  port: 8081

spring:
  config:
    import: optional:secret.yaml
  security:
    oauth2:
      client:
        address-api:
          clientId: ${address-api.clientId}
          clientSecret: ${address-api.clientSecret}
          accessTokenUri: ${address-api.accessTokenUri}
          expireCorrectionInSeconds: 20
        registration:
          address-api:
            clientId: ${address-api.clientId}
            clientSecret: ${address-api.clientSecret}
            authorizationGrantType: client_credentials
        provider:
          address-api:
            tokenUri: ${address-api.accessTokenUri}
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server}:${kafka.port}

keycloak:
  auth-server-url: ${kcloak.auth-server.protocol}://${kcloak.auth-server.host}:${kcloak.auth-server.port}
  realm: customer-service
  resource: customer-service
  bearer-only: true

auth:
  enabled: true
  ignored:
    urls: /customer-api/swagger-ui/**, /customer-api/api-docs, /customer-api/api-docs/*, /actuator/**

customer:
  file:
    url: src/main/resources/data/customers.json

rest:
  address-service:
    uri: ${address-api.protocol}://${address-api.host}:${address-api.port}/address-api/addresses

cache:
  clean:
    intervalInMilliseconds: 20000

management:
  endpoints:
    web:
      exposure:
        include: health, info, heapdump, threaddump, metrics
  info:
    env:
      enabled: true

info:
  contributors:
    - Ilker Yaman
    - Sinan Bulubay
    - Gizem Solum
    - Abdul Samet Altunsoy

spring-doc:
  packages-to-scan: com.nsc.customer.controller
  api-docs:
    enabled: true
    path: /customer-api/api-docs
  swagger-ui:
    path: /customer-api/swagger-ui