server:
  port: 8081

customer:
  file:
    url: src/main/resources/data/customers.json

management:
  endpoints:
    web:
      exposure:
        include: health, info, heapdump, threaddump, metrics
  info:
    env:
      enabled: true
info:
  contributors:
    - Ilker Yaman
    - Sinan Bulubay
    - Gizem Solum
    - Abdul Samet Altunsoy

spring-doc:
  packages-to-scan: com.nsc.customer.controller
  api-docs:
    enabled: true
    path: /customer-api/api-docs
  swagger-ui:
    path: /customer-api/swagger-ui

