server:
  port: 8082

keycloak:
  auth-server-url: http://192.168.229.129:38080
  realm: address-service
  resource: address-service
  bearer-only: true

auth:
  enabled: true
  ignored:
    urls: /address-api/swagger-ui/**, /address-api/api-docs, /address-api/api-docs/*, /actuator/**

address:
  file:
    url: src/main/resources/data/addresses.json

management:
  endpoints:
    web:
      exposure:
        include: health, info, heapdump, threaddump, metrics
  info:
    env:
      enabled: true

info:
  contributors:
    - Ilker Yaman
    - Sinan Bulubay
    - Gizem Solum
    - Abdul Samet Altunsoy

spring-doc:
  packages-to-scan: com.nsc.address.controller
  api-docs:
    enabled: true
    path: /address-api/api-docs
  swagger-ui:
    path: /address-api/swagger-ui

